# Your bot token
token: token here
# List of messages and their emoji-to-role mappings
messages:
  - message_id: 1501995003814215680  # Message ID to listen on
    # Mapping of emoji to role ID. 
    # Emoji can be a unicode emoji or discord emoji id obtained by using \:emoji:
    emoji_to_role:
      "💀": 808081607239008329
      "☀": 708081607239008329
  - message_id: 1502001042731176056  # Message ID to listen on
    # Mapping of emoji to role ID. 
    # Emoji can be a unicode emoji or discord emoji id obtained by using \:emoji:
    emoji_to_role:
      "<:khm:880215367425851393>": 208081607239008329
      "<:ogoo:880215419586240572>": 508081607239008329
# When set to true, bot will add missing reactions to messages on startup
add_reactions: true
